language: go

matrix:
  include:
  - go: 1.9
  - go: 1.10.x
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on
  - go: master
    env: GO111MODULE=on

before_install:
  - if [ $GO111MODULE != "on" ]; then
      curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh;
    fi
  - go get github.com/mattn/goveralls # for profiling coverage

install:
  - if [ $GO111MODULE == "on" ]; then
      go mod download;
    else
      dep ensure;
    fi

script:
  - go test -v ./...
  - goveralls -service=travis-ci -ignore=zendesk/mock/client.go

notifications:
  email: false
