language: go

go:
  - 1.9
  - 1.10.x
  - 1.11.x
  - master

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls # for profiling coverage

install:
  - dep ensure

script:
  - go test -v ./...
  - goveralls -service=travis-ci -ignore=zendesk/mock/client.go

notifications:
  email: false
